### ISSUE TITLE
How can pass VM Arguments?

### ISSUE THREAD

**Issue by renojjoseph** [dlemmermann/JPackageScriptFX#10]
I have successfully made the deb installer from my application and installed it. But the application is not starting when the icon is double clicked. Taken the stack trace from terminal

```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ae9e832'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/naming/NamingException
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:186)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at saramsfx.MysqlDBConnector.dbConnector(MysqlDBConnector.java:44)
	at saramsfx.LoginController.initialize(LoginController.java:68)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2655)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2516)
	at saramsfx.Home.start(Home.java:21)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

```
I am using jfoenix controls in my application. Hence the following VM arguments should be passed

```
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports javafx.base/com.sun.javafx.event=com.jfoenix

```
I have tried to pass it like this in the build_app_linux.sh

```
# ------ RUNTIME IMAGE ------------------------------------------------------
# Use the jlink tool to create a runtime image for our application. We are
# doing this in a separate step instead of letting jlink do the work as part
# of the jpackage tool. This approach allows for finer configuration and also
# works with dependencies that are not fully modularized, yet.

echo "creating java runtime image"
$JAVA_HOME/bin/jlink \
  --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
  --add-opens=java.base/java.lang.reflect=com.jfoenix \
  --add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix \
  --add-exports javafx.base/com.sun.javafx.binding=com.jfoenix \
  --add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix \
  --add-exports javafx.base/com.sun.javafx.event=com.jfoenix \
  --add-modules "${detected_modules}${manual_modules}" \
  --strip-native-commands \
  --no-header-files \
  --no-man-pages  \
  --compress=2  \
  --strip-debug \
  --include-locales=en,de \
  --output target/java-runtime
```
But build fails and gives the error
```
java home: /opt/openjdk/jdk-17
project version: 1.0-SNAPSHOT
app version: 1.0.0
main JAR file: Sarams-1.0-SNAPSHOT.jar
detecting required modules
detected modules: java.base,java.desktop,java.scripting,java.sql,jdk.jfr,jdk.unsupported
manual modules: ,jdk.crypto.ec,jdk.localedata
creating java runtime image
Error: unknown option: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
Usage: jlink <options> --module-path <modulepath> --add-modules <module>[,<module>...]
Use --help for a list of possible options
Creating installer of type deb
Specified runtime image directory runtime-image: target/java-runtime does not exist
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```
Can you please suggest a method to add these vm arguments?

**Comment by dlemmermann** [comment]
I think those need to be passed to the jpackage tool, not jlink. Find this line in the scripts: --java-options

**Comment by dlemmermann** [comment]
But looking at the error I do not understand why you think it is related to that.

**Comment by dlemmermann** [comment]
Try to see if the JAR that contains the missing class can be found in the target/libs folder. This is where the script puts everything that seems to be required to run the app.

**Comment by mipastgt** [comment]
I guess you just have to add "java.naming" to the manual_modules.

**Comment by renojjoseph** [comment]
@dlemmermann "classes were loaded from 'unnamed module @6ae9e832'" points to VM arguments
I have also tried to add it to the package tool but getting the same error.

**Comment by mipastgt** [comment]
"WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ae9e832" is a standard warning if JavaFX is not used from the module path. Just forget it. It has nothing to do with your problem.

**Comment by renojjoseph** [comment]
@mipastgt My application is single modular and I have 3 automatic modules in my module-info.java viz jasperreports, webcam.capture and imgscalr.lib. I have done nothing to add these to the manual_modules. But these jars are present in the app folder of the installer.

**Comment by mipastgt** [comment]
Remove the module-info.java. This tutorial is for non-modular applications.

**Comment by renojjoseph** [comment]
Removed the module-info.java ,rebuild the installer and installed. Now the stack trace is

```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @e11173d'
java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2541)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2516)
	at saramsfx.Home.start(Home.java:21)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by renojjoseph** [comment]
I am able to run the fat jar made using assembly plugin. But can,t open windows where jfoenix controlls are used. If I run the fat jar with a .sh file passing VM arguments application works fine.

**Comment by renojjoseph** [comment]
My Home Class is

```
public class Home extends Application {
	private static Scene scene;

	@Override
	public void start(Stage primaryStage) {

		try {
			final FXMLLoader loader = new FXMLLoader();
			loader.setLocation((getClass().getResource("/fxml/Login.fxml")));
			final Parent root = (Parent) loader.load();
			scene = new Scene(root, 800, 500);
			scene.getStylesheets().add(getClass().getResource("/css/person.css").toExternalForm());
			primaryStage.setScene(scene);
			showStage(primaryStage);

		} catch (final Exception e) {
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {
		launch(args);
	}

	public static Scene getScene() {

		return scene;
	}
}
```

**Comment by dlemmermann** [comment]
Closing ticket as it is no longer related to this project.
